#!/bin/sh

PROG="nodejs"
PROG_PATH="/data/app/$PROG"
MSG_PREFIX=" *"
echo "$MSG_PREFIX start install $PROG"

if [ -d "$PROG_PATH" ] ; then
	rm -rf $PROG_PATH
fi

mkdir -p $PROG_PATH

cp -v -n -r bin $PROG_PATH/
cp -v -n -r include $PROG_PATH/
cp -v -n -r lib $PROG_PATH/
cp -v -n -r share $PROG_PATH/

ln  -f -s $PROG_PATH/bin/node /usr/bin/nodejs && ln -f -s $PROG_PATH/bin/node /usr/bin/node && ln -f -s $PROG_PATH/bin/npm /usr/bin/npm

echo "$MSG_PREFIX install sucess $PROG"

$PROG -v
